---
- name: Collect and archive system logs
  ansible.builtin.archive:
    path: 
      - /var/log/auth.log
      - /var/log/syslog
    path_to_be_collected: /mnt/esx/var/log/
    dest: "/forensic_storage/logs_{{ inventory_hostname }}.tar.gz"

- name: Collect and archive user data
  ansible.builtin.archive:
    path: /mnt/esx/home/
    dest: "/forensic_storage/userdata_{{ inventory_hostname }}.tar.gz"

- name: Collect and archive configuration files
  ansible.builtin.archive:
    path:
      - /mnt/esx/etc/passwd
      - /mnt/esx/etc/group
    dest: "/forensic_storage/config_files_{{ inventory_hostname }}.tar.gz"
