---
# Main entry for the Forensic File Collection role

# Common Tasks for collecting disk images from ESXi environments

- name: get the username running the deploy
  become: false
  local_action: command whoami
  register: username_on_the_host
  delegate_to: localhost


- name: Ensure directory for storing collected files exists
  ansible.builtin.file:
    path: "{{ playbook_dir }}/{{ ForenDataDirName }}"
    state: directory
    owner: "{{ username_on_the_host.stdout }}"
    group: "{{ username_on_the_host.stdout }}"
    mode: '0755'
  delegate_to: localhost

- name: Ensure directory for storing VM disks exists
  ansible.builtin.file:
    path: "{{ playbook_dir }}/{{ ForenDataDirName }}/ESXi-Artifacts"
    state: directory
    owner: "{{ username_on_the_host.stdout }}"
    group: "{{ username_on_the_host.stdout }}"
    mode: '0755'
  delegate_to: localhost

- name: Collect data from vCenter
  include_tasks: artifacts_vcenter_collection.yaml
  when: target_environment == 'vcenter'
  tags: 
    - vcenter
    - disk_acquistion
    - all_collection

- name: Collect data from ESXi
  include_tasks: artifacts_esxi_collection.yaml
  when: target_environment == 'esxi'
  tags: 
    - esxi
    - disk_acquistion
    - all_collection
