- name: Query a the vmem snapshot on a datastore
  community.vmware.vsphere_file:
    host: '{{ vcenter_hostname }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    datacenter: '{{ vcenter_datacenter }}'
    datastore: '{{ item }}'
    path: "{{ forensics_VM_name }}/{{ forensics_VM_name }}-Snapshot{{ item }}.vmem"
    state: file
    validate_certs: "{{ CERT_VALIDATION }}"
  delegate_to: localhost
  ignore_errors: yes
  register: file_path_result
  loop: '{{ vcenter_datastore }}'
  with_sequence: start=0 end={{ last_snapshot }}
  vars:
    last_snapshot: 3


# - name: Fetch a the nvram from vCenter
#   uri:
#     url: "https://10.0.1.15/folder/CentOS-8/CentOS-8.nvram?dsName=T3_SSD_2TB_2_Dev&dcPath=Moonlight_Datacenter"
#     user: "{{ vcenter_username }}"
#     password: "{{ vcenter_password }}"
#     validate_certs: no
#     method: "get"
#     dest: ./{{ forensics_VM_name }}.vmem