---
- name: include vmsn
  include_tasks: vmsn.yml
  tags: Mem_Acquistion
  loop: "{{ compromised_VM_names }}"
  loop_control:
    loop_var: VM_Name

- name: include vmem
  include_tasks: vmem.yml
  tags: Mem_Acquistion
  loop: "{{ compromised_VM_names }}"
  loop_control:
    loop_var: VM_Name
