---
- name: Ensure directory for storing collected files exists
  ansible.builtin.file:
    path: "{{ playbook_dir }}/{{ ForenDataDirName }}"
    state: directory
    owner: "{{ username_on_the_host.stdout }}"
    group: "{{ username_on_the_host.stdout }}"
    mode: '0755'
  delegate_to: localhost

- name: Ensure directory for storing VM disks exists
  ansible.builtin.file:
    path: "{{ playbook_dir }}/{{ ForenDataDirName }}/ioc_sweep_mount_point"
    state: directory
    owner: "{{ username_on_the_host.stdout }}"
    group: "{{ username_on_the_host.stdout }}"
    mode: '0755'
  delegate_to: localhost

- name: Define ioc_sweep_mount_point path
  set_fact:
    ioc_sweep_mount_point: "{{ playbook_dir }}/{{ ForenDataDirName }}/ioc_sweep_mount_point"


- name: Mount ESXi filesystem using SSHFS
  ansible.builtin.shell:
    cmd: "sshfs -o -reconnect {{ ansible_user }}@{{ esxi_host }}:/ '{{ ioc_sweep_mount_point }}' "
  ignore_errors: yes  # Depending on your error handling strategy

- name: Define thor-lite path
  set_fact:
    thor_path: "{{ playbook_dir }}/tools/thor"

- name: Run THOR Lite scan on the mounted ESXi filesystem
  ansible.builtin.shell:
    cmd: "{{ thor_path }}/thor-lite-linux-64 -a FileScan --alldrives -p '{{ mount_point }}'"
  register: thor_scan_result

