---
# Tasks for collecting disk images from ESXi environments

- name: Ensure directory for storing collected files exists
  ansible.builtin.file:
    path: "{{ playbook_dir }}/{{ ForenDataDirName }}"
    state: directory
    mode: '0755'

- name: Ensure directory for storing VM disks exists
  ansible.builtin.file:
    path: "{{ playbook_dir }}/{{ ForenDataDirName }}/Disks"
    state: directory
    mode: '0755'

- name: Placeholder for ESXi specific disk collection tasks
  debug:
    msg: "Implement ESXi specific tasks for disk image collection here."
