---

- community.vmware.vmware_export_ovf:
    hostname: '{{ esxi_hostname }}'
    username: '{{ esxi_username }}'
    password: '{{ esxi_password }}'
    name: '{{ item }}'
    export_with_images: true
    export_dir: "{{ playbook_dir }}/{{ ForenDataDirName }}/Disks"
    validate_certs: '{{ CERT_VALIDATION }}'
  delegate_to: localhost
  loop: "{{ compromised_VM_names }}"