---

- name: Provide information about a standalone ESXi server
  community.vmware.vmware_about_info:
    hostname: '{{ esxi_hostname }}'
    username: '{{ esxi_username }}'
    password: '{{ esxi_password }}'
    validate_certs: '{{ CERT_VALIDATION }}'
  delegate_to: localhost
  register: esxi_about_info

- name: Print disk facts
  debug:
    msg: "{{ esxi_about_info }}"

- name: Gather info from standalone ESXi server having datacenter as 'ha-datacenter'
  community.vmware.vmware_datastore_info:
    hostname: '{{ esxi_hostname }}'
    username: '{{ esxi_username }}'
    password: '{{ esxi_password }}'
    datacenter_name: "ha-datacenter"
    validate_certs: '{{ CERT_VALIDATION }}'
  delegate_to: localhost
  register: info_standalone_esxi_datastore

- name: Print info from standalone ESXi datastore
  debug:
    msg: "{{ info_standalone_esxi_datastore }}"

- name: Gather disk info from virtual machine using name
  community.vmware.vmware_guest_disk_info:
    hostname: '{{ esxi_hostname }}'
    username: '{{ esxi_username }}'
    password: '{{ esxi_password }}'
    datacenter: ha-datacenter
    name: '{{ item }}'
    validate_certs: '{{ CERT_VALIDATION }}'
  delegate_to: localhost
  loop: "{{ compromised_VM_names }}"
  register: disk_info_compromised_vm

- name: Print info from compromised vm 
  debug:
    msg: "{{ disk_info_compromised_vm }}"


- name: Gather info about ESXi Host
  community.vmware.vmware_host_config_info:
    hostname: '{{ esxi_hostname }}'
    username: '{{ esxi_username }}'
    password: '{{ esxi_password }}'
    esxi_hostname: '{{ esxi_hostname }}'
    validate_certs: '{{ CERT_VALIDATION }}'
  delegate_to: localhost


- community.vmware.vmware_export_ovf:
    hostname: '{{ esxi_hostname }}'
    username: '{{ esxi_username }}'
    password: '{{ esxi_password }}'
    name: '{{ item }}'
    export_with_images: true
    export_dir: "{{ playbook_dir }}/{{ ForenDataDirName }}"
    validate_certs: '{{ CERT_VALIDATION }}'
  delegate_to: localhost
  loop: "{{ compromised_VM_names }}"