---
# Main entry for the Forensic File Collection role

- name: Collect data from vCenter
  include_tasks: disk_image_vcenter_collection.yml
  when: target_environment == 'vcenter'
  tags: 
    - vcenter
    - disk_acquistion
    - all_collection

- name: Collect data from ESXi
  include_tasks: disk_image_esxi_collection.yml
  when: target_environment == 'esxi'
  tags: 
    - esxi
    - disk_acquistion
    - all_collection